# Generated by Django 5.1.5 on 2025-03-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='verifier/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='verifier/profile_pictures/'),
        ),
    ]
