# Generated by Django 5.1.5 on 2025-04-24 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0005_storeddocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeddocument',
            name='document',
        ),
    ]
